### ISSUE TITLE
Set postman to update bearer token automatically on login

### ISSUE THREAD

**Issue by fhsbatista** [fhsbatista/journal#9]

**Comment by fhsbatista** [comment]
Done!

**Comment by fhsbatista** [comment]
We can do this by using "Tests" that's available on collection's page. There we can write a javascript that:
1) Get the response and find the token in headers
2) Update and env var with the new token.

Obs: We can debug it using the postman's console.

Example:
![image](https://github.com/fhsbatista/journal/assets/18507203/cd38df8e-7a42-4853-9fe9-c2b421d4331e)

**Comment by fiaz-ali** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
renwoox, @keyiiiii, @hustxiaoc, @LusciousLace, @ChinW, @andmironov, @cs-shares-guy, @liwtattbs2019, @alobanov, @CannonVegetable, @dladowitz, @jsonwen, @fonov, @cm112344, @rameerez, @Markshall, @imannaz, @scriptsman, @d4nyll, @BiswajitDtta, @chadsr, @chenleicrm, @Salamaleko, @alexej520, @Ciaran0, @lupelius, @wintermutt, @meoz, @mdcpepper, @Roosso, @onuryavuz, @rtzll, @ivanessence, @juno, @rys-acme, @Diversified1, @jccherry, @divizdev, @Pikachu2Github, @patie, @benjioh5, @stuartjk, @bchoubert, @daronjay, @alexinblock, @yannickboog, @dymissy, @orobogenius, @NeonSpork, @ajaykarwaldandevri, @StefanoGR, @xerod, @barnumbirr, @mac-s-g, @trubel, @CoxxA, @AlvisBrown, @danny-englander, @firede, @jfrausto, @quanack, @ryanpcmcquen, @csaper, @kimtaejin3, @FiberJW, @arden, @CapitanRedBeard, @lexybarton, @eznix86, @mcpeng, @therealwolf42, @daffavcd, @drondov, @leakeyqq, @mr-bloom, @burnaDLX, @noctifer20, @nearontheinside, @MrCSharp22, @dongabrielli, @krocon, @ik5, @ankitm27, @Jannchie, @afarukcali, @pengpengliu, @rashad, @romejiang, @ElRakabawi, @mdjordjevic, @wmira, @spences10, @jhrr, @mattiaerre, @apski, @superdcc, @VJELO, @pramodpalutla, @t32kdkast, @tuxcanfly, @idootop, @SeanZoR, @wangshijun, @bennetfabian, @rizidoro, @danielmilner, @dog5tar, @lafabo, @shikakun, @mariusbolik, @dulumao, @ramnaq, @MarcelJurtz, @fredmp, @hanesauce, @mhmyu, @aabril, @whathejoe, @Herklos, @heartfield, @brandon93s, @dice2019, @kristijandraca-xx, @Dvorson, @Dollarman, @DanielPetelin, @simonamdev, @KorovaKoins, @HoangTuan110, @nejdetkadir, @flieks, @ghost, @xeoneux, @eliasbauer1, @alexbabichev, @leandrodragani, @Jason-Black, @holoiii, @bskidan, @P233, @exzzy22, @catwhocode, @miumiuplus, @riussi, @remoe, @forestlioooooo, @srkn-gndz, @Caskia
